---
- name: check which mysql version is used
  community.mysql.mysql_info:
    filter: version
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  register: mysql_version

- name: get all users that have no password or authentication_string on MySQL version >= 5.7.6
  community.mysql.mysql_query:
    query:
      - select user,host,password from mysql.user where (length(password)=0 or password="") and (length(authentication_string)=0 or authentication_string="") and user NOT IN ('mysql.sys', 'mysqlxsys', 'mariadb.sys');
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  register: mysql_users_wo_passwords_or_auth_string
  when:
    - mysql_version.version.full is version('5.7.6', '>=')

- name: assert that there are no users that have no password or authentication_string on MySQL version >= 5.7.6
  assert:
    that:
      - users_wo_password_or_auth_string == ""

- name: get all users that have no password on MySQL version < 5.7.6
  community.mysql.mysql_query:
    query:
      - select user,host,password from mysql.user where (length(password)=0 or password="") and user NOT IN ('mysql.sys', 'mysqlxsys', 'mariadb.sys');
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  register: mysql_users_wo_passwords
  when:
    - mysql_version.version.full is version('5.7.6', '<')

- name: assert that there are no users that have no password on MySQL version < 5.7.6
  assert:
    that:
      - users_wo_password == ""
  when:
    - mysql_version.version.full is version('5.7.6', '<')
