---
dependency:
  name: galaxy
  options:
    role-file: molecule/os_hardening/requirements.yml
driver:
  name: docker
lint: |
  yamllint roles/os_hardening/ molecule/os_hardening/ .github/workflows/os_hardening.yml
  ansible-lint roles/os_hardening/
platforms:
  - name: instance
    image: "rndmh3ro/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    tty: True
    environment:
      container: docker
provisioner:
  name: ansible
  vvv: True
verifier:
  name: inspec
