---
- name: wrapper playbook for kitchen testing "ansible-os-hardening" with custom vars for testing
  hosts: all
  become: true
  collections:
    - devsec.hardening
  tasks:
    - name: set ansible_python_interpreter to "/usr/bin/python3" on fedora
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
      when: ansible_facts.distribution == 'Fedora'

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
      when: ansible_facts.os_family == 'Debian'
    - name: install required tools on debian
      apt:
        name: procps
      when: ansible_facts.os_family == 'Debian'
    - name: install required tools on fedora
      dnf:
        name:
          - python
          - findutils
          - procps-ng
      when: ansible_facts.distribution == 'Fedora'
    - name: create recursing symlink to test minimize access
      shell: "rm -f /usr/bin/zzz && ln -s /usr/bin /usr/bin/zzz"
      changed_when: false
