---
- name: Converge playbook for testing devsec.hardening.macos_hardening
  hosts: all
  become: true
  tasks:
    - name: Include macos_hardening role
      ansible.builtin.include_role:
        name: macos_hardening
  vars:
    macos_hardening_enabled: true
    macos_profile_install: false
    macos_login_window_message: "Authorized access only."
    macos_policy_banner_content: "This computer system is private property. Authorized access only."
