namespace: devsec
name: hardening
version: 8.4.0
readme: README.md
authors:
  - dev-sec <hello@dev-sec.io>
description: 'This collection provides battle tested hardening for Linux, SSH, nginx, MySQL'
license:
  - Apache-2.0
license_file: ''
tags:
  - devsec
  - hardening
  - centos
  - ubuntu
  - debian
  - nginx
  - mysql
  - openssh
  - apache_hardening
  - mysql_hardening
  - nginx_hardening
  - os_hardening
  - ssh_hardening
dependencies:
  ansible.posix: '>=1.0.0'
  community.crypto: '>=1.0.0'
  community.general: '>=1.0.0'
  community.mysql: '>=1.3.0'
repository: 'https://github.com/dev-sec/ansible-collection-hardening/'
homepage: 'https://dev-sec.io/'
issues: 'https://github.com/dev-sec/ansible-collection-hardening/issues'
build_ignore:
  - codecov.yml
  - .github
  - .gitattributes
  - .gitignore
  - hacking
  - requirements.txt
  - test-requirements.txt
  - tests
  - .tox
  - tox.ini
  - .yamllint
