#!/bin/sh
ALIAS_CMD="$(echo ""$0"" | sed -e 's?/sbin/??')"

case "$ALIAS_CMD" in
    start|stop|restart|reload|status)
        exec service $1 $ALIAS_CMD
        ;;
esac

case "$1" in
    list )
        exec service --status-all
        ;;
    reload-configuration )
        exec service $2 restart
        ;;
    start|stop|restart|reload|status)
        exec service $2 $1
        ;;
    \?)
        exit 0
        ;;
esac

