---
- name: set fact for os_immutable_fs
  set_fact: 
    ansible_package_use: "community.general.rpm_ostree_pkg" 
    rpm_ostree_needs_reboot: ""
  when: os_immutable_fs | bool

- name: Include hardening tasks
  ansible.builtin.include_tasks: hardening.yml
  when: os_hardening_enabled | bool
  tags:
    - always

- name: Reboot if ostree_immutable needs_reboot is true
  ansible.builtin.reboot:
    msg: "Rebooting to install packages"
    pre_reboot_delay: 0
  when:
    - os_immutable_fs | bool
    - rpm_ostree_needs_reboot

- name: Wait for ostree system to be up
  ansible.builtin.wait_for_connection:
    delay: 20
  when:
    - os_immutable_fs | bool 
    - rpm_ostree_needs_reboot