---
# configuration tasks for rpm_ostree systems
# selected when os_immutable_fs == true
# basic tasks taken from ./yum.yml
- name: Remove deprecated or insecure packages | package-01 - package-09
  community.general.rpm_ostree_pkg:
    name: "{{ os_security_packages_list }}"
    state: absent
  when: os_security_packages_clean | bool