---
# reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests
name: "Feature request"
description: "Suggest an idea for this project."
labels: [
  "enhancement"
]
body:
  - type: markdown
    attributes:
      value: |
        Requesting a new feature or enhancement is following some simple rules:

        - **Check**, if the feature is already requested
        - **Describe** what your feature will bring to the community
        - **Explain** the criteria to fulfill the request
        - **Add** more details like mock ups, attachments, lists, screenshots
        - **Follow Up** in the discussion to the feature

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Solution"
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional information"
      description: Add any other context or screenshots about the feature request here.
      value: |
        ...
    validations:
      required: false
