---
- name: Install pip
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-setuptools
    state: present

- name: Install pam-tester
  ansible.builtin.pip:
    name: pam-tester
    state: present
    executable: /usr/bin/pip3

- name: set password for test
  set_fact:
    test_pw: "myTest!pw"

- name: Set locale for test
  ansible.builtin.set_fact:
    locale: en_US.UTF-8
  when:
    - ansible_facts.os_family == 'RedHat'
    - ansible_facts.distribution_major_version < '8'

- name: Create testuser
  ansible.builtin.user:
    name: testuser
    password: "{{ test_pw | password_hash('sha512') }}"

- name: Check successful login with correct password
  ansible.builtin.shell:
    cmd: /usr/local/bin/pam-tester --user testuser --password {{ test_pw }}
  environment:
    TMPDIR: /var/tmp
    LC_ALL: "{{ locale | default('C.UTF-8') }}"
    LANG: "{{ locale | default('C.UTF-8') }}"

- name: Check unsuccessful login with incorrect password
  ansible.builtin.shell:
    cmd: /usr/local/bin/pam-tester --user testuser --password {{ test_pw }}fail --expectfail
  environment:
    TMPDIR: /var/tmp
    LC_ALL: "{{ locale | default('C.UTF-8') }}"
    LANG: "{{ locale | default('C.UTF-8') }}"
  with_sequence: count=6

- name: Check unsuccessful login, with correct password (lockout)
  ansible.builtin.shell:
    cmd: /usr/local/bin/pam-tester --user testuser --password {{ test_pw }} --expectfail
  environment:
    TMPDIR: /var/tmp
    LC_ALL: "{{ locale | default('C.UTF-8') }}"
    LANG: "{{ locale | default('C.UTF-8') }}"

- name: Wait for account to unlock
  ansible.builtin.pause:
    seconds: 20

- name: Check successful login
  ansible.builtin.shell:
    cmd: /usr/local/bin/pam-tester --user testuser --password {{ test_pw }}
  environment:
    TMPDIR: /var/tmp
    LC_ALL: "{{ locale | default('C.UTF-8') }}"
    LANG: "{{ locale | default('C.UTF-8') }}"
