---
- name: Prepare playbook for kitchen testing "ansible-postgres-hardening" with custom settings
  become: true
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  vars_files:
    - geerlingguy_postgresql_vars.yml
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "python3-apt"
        update_cache: true
      ignore_errors: true # noqa ignore-errors

    - name: Installing PostgreSQL
      ansible.builtin.include_role:
        name: geerlingguy.postgresql
