---
- name: Prepare OpenBSD host
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Use Python 3 on OpenBSD
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
      changed_when: false
      when: lookup('env', 'MOLECULE_DISTRO') == 'openbsd7'

- name: Wrapper playbook for kitchen testing "ansible-ssh-hardening" with default settings
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  tasks:
    - name: Include ssh_hardening role
      ansible.builtin.include_role:
        name: devsec.hardening.ssh_hardening
  vars:
    sftp_enabled: false
