---
- name: Wrapper playbook for kitchen testing "ansible-nginx-hardening" with custom settings
  become: true
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  vars:
    nginx_ppa_use: true
    nginx_ppa_version: stable
  tasks:
    - name: Include nginx_hardening role
      ansible.builtin.include_role:
        name: devsec.hardening.nginx_hardening
