---
dependency:
  name: galaxy
  options:
    role-file: molecule/nginx_hardening/requirements.yml
driver:
  name: docker
lint: |
  yamllint roles/nginx_hardening/ molecule/nginx_hardening/ .github/workflows/nginx_hardening.yml
  ansible-lint roles/nginx_hardening/
platforms:
  - name: instance
    image: "rndmh3ro/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    tty: true
    environment:
      container: docker
provisioner:
  name: ansible
  vvv: true
verifier:
  name: inspec

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # role not idempotent
    - verify
    - destroy
