---
dependency:
  name: galaxy
  options:
    role-file: molecule/os_hardening_vm/requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  # we need to name every instance differently to start multiple VMs on the same host (parallelization)
  # since we also need to use different OS users to run the tests because of how molecule operates,
  # the VM names must be predictable by OS user (to clean up canceled runs)
  - name: ${USER}
    box: ${MOLECULE_DISTRO}
    memory: 1024
    cpus: 2
provisioner:
  name: ansible
  options:
    diff: true
  env:
    ANSIBLE_PIPELINING: "True"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
verifier:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - verify
    - destroy
