---
- name: Disable systemd-socket activation
  ansible.builtin.systemd:
    name: ssh.socket
    state: stopped
    enabled: false
    masked: true

- name: Remove ssh service systemd-socket file
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/ssh.service.d/00-socket.conf
    - /etc/systemd/system/ssh.service.requires/ssh.socket
    - /etc/systemd/system/sockets.target.wants/ssh.socket

- name: Ensure ssh service is started after disabling socket activation
  ansible.builtin.systemd:
    name: "{{ sshd_service_name }}"
    state: started
    enabled: true
