---
- name: Include hardening tasks
  ansible.builtin.include_tasks: hardening.yml
  args:
    apply:
      become: true
  when: ssh_hardening_enabled | bool

- name: Reboot if ostree_immutable needs_reboot is true
  ansible.builtin.reboot:
    msg: "Rebooting to install packages"
    pre_reboot_delay: 0
  when:
    - ssh_ostree_needs_reboot | bool
    - ssh_immutable_fs | bool
  tags: ostree_reboot

- name: Wait for ostree system to be up
  ansible.builtin.wait_for_connection:
    delay: 20
  when:
    - ssh_ostree_needs_reboot | bool
    - ssh_immutable_fs | bool 
  tags: ostree_reboot
