---
galaxy_info:
  author: Sebastian Gumprich
  description: This Ansible role provides secure nginx configurations. http://dev-sec.io/
  company: Hardening Framework Team
  license: Apache License 2.0
  min_ansible_version: 2.9.10
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Amazon
  galaxy_tags:
    - system
    - security
    - hardening
    - nginx
dependencies: []
