---
- name: Safari | Disable auto-open safe downloads in Safari
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.Safari
    key: AutoOpenSafeDownloads
    type: bool
    value: false

- name: Safari | Enable fraudulent website warning in Safari
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.Safari
    key: WarnAboutFraudulentWebsites
    type: bool
    value: true

- name: Safari | Enable cross-site tracking prevention in Safari
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.Safari
    key: BlockStoragePolicy
    type: int
    value: 2

- name: Safari | Enable Private Click Measurement advertising protection
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.Safari
    key: "WebKitPreferences.privateClickMeasurementEnabled"
    type: bool
    value: true

- name: Safari | Enable full website address display in Safari
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.Safari
    key: ShowFullURLInSmartSearchField
    type: bool
    value: true

- name: Safari | Enable status bar in Safari
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.Safari
    key: ShowOverlayStatusBar
    type: bool
    value: true

- name: Safari | Enable Secure Keyboard Entry in Terminal
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.Terminal
    key: SecureKeyboardEntry
    type: bool
    value: true
