---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codespell:
    uses: "dev-sec/.github/.github/workflows/codespell.yml@68f5f44bcf658b9216549d968d02b25e80ceb4cb" # main
    with:
      ignore_words_list: "chage,BOOTUP"
